### ISSUE TITLE
Sometimes eth-sdk fails to generate client

### ISSUE THREAD

**Issue by Pzixel** [dethcrypto/eth-sdk#106]
I wasn't able to create a MRE to bring any code that reproduces an issue but I hope it may be clear from the error itself:

> ❯ yarn eth-sdk                                                 
> yarn run v1.22.17
> Loaded sdk definition from /Users/pzixel/Documents/Repos/test/eth-sdk
> ✔ Getting ABIs
> ⠙ Generating client/var/folders/_w/s45kr_gx6q1f75q2p7ljft100000gn/T/eth-sdk-64037-gNxOCe0UMMR6/index.ts (16,117): Namespace '"/var/folders/_w/s45kr_gx6q1f75q2p7ljft100000gn/T/eth-sdk-64037-gNxOCe0UMMR6/types/index"' has no exported member 'mainnet'.
> /var/folders/_w/s45kr_gx6q1f75q2p7ljft100000gn/T/eth-sdk-64037-gNxOCe0UMMR6/index.ts (16,117): Namespace '"/var/folders/_w/s45kr_gx6q1f75q2p7ljft100000gn/T/eth-sdk-64037-gNxOCe0UMMR6/types/index"' has no exported member 'mainnet'.
> ✖ Generating client
> ```
> Error: TypeScript compilation failed.
> 
>     at /Users/pzixel/Documents/Repos/test/node_modules/@dethcrypto/eth-sdk/src/client/transpileClient.ts:39:15
>     at Array.map (<anonymous>)
>     at transpileClient (/Users/pzixel/Documents/Repos/test/node_modules/@dethcrypto/eth-sdk/src/client/transpileClient.ts:14:13)
>     at async generateSdk (/Users/pzixel/Documents/Repos/test/node_modules/@dethcrypto/eth-sdk/src/client/index.ts:23:3)
> ```

I tried to downgrade packages version but it still returns this error.

**Comment by daniel-ivanco** [comment]
Had the same issue. I've tried to update all @typechain related dependencies to the latest versions and it started to work.

**Comment by krzkaczor** [comment]
As @daniel-ivanco mentioned -- probably a version mismatch. Please reopen if you have a repro.
