### ISSUE TITLE
Unable to fetch ABI for USDC?

### ISSUE THREAD

**Issue by ar4sdoteth** [dethcrypto/eth-sdk#49]
When adding the USDC address `0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48` it seems like etherscan doesn't accept it as a valid request. Changing the address to UniswapsV2router02 address and leaving the key as "usdc" yeilds a result and creates the ABI. I find that very odd.

I've reinstalled the packages and started from scratch with defaults, only adding DAI and USDC to the config. (Previously I had also tried my own Etherscan/RPC API's thinking that was the issue)

config.json
```
{
  "contracts": {
    "mainnet": {
      "tokens": {
        "COMP": "0xc00e94cb662c3520282e6f5717214004a7f26888",
        "DAI": "0x6b175474e89094c44da98b954eedeac495271d0f",
        "USDC": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
      },
      "compound": {
        "comptroller": "0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B",
        "comptrollerImpl": "0x374ABb8cE19A73f2c4EFAd642bda76c797f19233",
        "treasury": "0x2775b1c75658be0f640272ccb8c72ac986009e38"
      }
    }
  }
}
```
CLI error when running `yarn eth-sdk`

```
✖ Getting ABIs
Error: missing revert data in call exception (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48\",\"data\":\"0x5c60da1b\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://mainnet.infura.io/v3/0993a4f4500c4fff88649d28b331898c"}, data="0x", code=CALL_EXCEPTION, version=providers/5.5.0)
```

**Comment by krzkaczor** [comment]
Thanks for the report -- we'll investigate this. 

As a quick workaround, you can simply copy USDC abi and place it manually in abi dir (`eth-sdk/abi/{network}/{name}.json`)

**Comment by ar4sdoteth** [comment]
Yeah I will do that so I can move on. Thank you for building making this, it's exactly what I spent a couple of days looking for.

I just noticed as well. If I spin it up with USD: uniswapv2router02 address, and then changed it to the correct USDC address I do not get the error. (Probably it doesn't fetch if an ABI exists with the key name? The ABI isn't updated either)

thanks again.
