### ISSUE TITLE
Clearing vite-cache on dev-build

### ISSUE THREAD

**Issue by wottpal** [dethcrypto/eth-sdk#54]
Hey, (sorry it's me again). 
I noticed one more problem with vite which cost me a lot of time understanding yesterday :D I think this should be added to the `dev` task or at least to the vite-example-readme :)

When you change the eth-sdk config and re-generate types (via `yarn eth-sdk`) the vite-dev-bundle doesn't notice the change – even when you restart the `dev`-task (via `yarn dev` or `npx vite`). That's because on its first dev-build it caches a version of the `eth-sdk-client` within `node_modules/.vite`. You can change that behavior forcing vite to clear the cache folder every time when you restart the dev-server/-build with `npx vite --force`.

My versions (if they make any difference):

```console
➜  vite-react node --version
v16.13.0
➜  vite-react npm --version
8.1.4
➜  vite-react yarn --version
1.22.17
➜  vite-react npx vite --version
vite/2.6.14 darwin-arm64 node-v16.13.0
➜  vite-react npx eth-sdk --version
0.2.2
```

**Comment by hasparus** [comment]
Howdy 👋 Nice catch!

I've been actually trying to get this to work using Vite's `optimizeDeps`, but `vite --force` seems to be the better option.

This PR should help: https://github.com/dethcrypto/eth-sdk/pull/56
