### ISSUE TITLE
Add known types in config file to support Polymorphism

### ISSUE THREAD

**Issue by agcty** [dethcrypto/eth-sdk#64]
Been playing around with eth-sdk and so far it has been pretty amazing. However, one thing on my wish-list is being able to narrow down types in the config.

I'm thinking of something like this:

```javascript
 moonriver: {
      fraxBond: "0xE2F71c68db7ECC0c9A907AD2E40E2394c5CAc367",
      frax: {
        address: "0x1A93B23281CC1CDE4C4741353F3064709A16197d",
        as: ["ERC20"],
      },
 },
```

my reasoning is that when you already know a contract is of type ERC20 for example, you could supply that information to eth-sdk which will then not only have it extend from BaseContract, but also extend from ERC20. This would then make it possible to iterate over a list of ERC20s because they have the same narrowed-down base.

**Comment by agcty** [comment]
maybe it would be also possible to allow extending from local classes

**Comment by agcty** [comment]
Nevermind, as long as the functions overlap you can iterate over a list of tokens without polymorphism, closing this issue, not sure if something like narrowing the type makes sense

**Comment by krzkaczor** [comment]
Yes, exactly you can just create your own typescript interface like `Erc20Like` with a minimal set of methods and thanks to TypeScript's structural typing it will work.
