### ISSUE TITLE
Polygonscan needs an API key

### ISSUE THREAD

**Issue by hasparus** [dethcrypto/eth-sdk#84]
We can't fetch ABI from Polygon without an API key, and the config does not allow to specify multiple etherscan keys.

```
Error: Can't find mainnet abi for 0x7ceb23fd6bc0add59e62ac25578270cff1b9f619. Msg: {
  "status": "0",
  "message": "NOTOK",
}
```

Take a look at https://github.com/dethcrypto/eth-sdk/pull/83/files. (Run `pnpm eth-sdk` in `packages/throwaway` to see the error.)

**Comment by ar4s-eth** [comment]
seconded lol.

**Comment by hasparus** [comment]
Fixed in https://github.com/dethcrypto/eth-sdk/releases/tag/%40dethcrypto%2Feth-sdk%400.3.1
