### ISSUE TITLE
Allow using Provider instead of Signer when creating SDK.

### ISSUE THREAD

**Issue by Pzixel** [dethcrypto/eth-sdk#95]
Consider following code:

```ts
import { getMainnetSdk } from '@dethcrypto/eth-sdk-client' // yay, our SDK! It's tailored especially for our needs

const sdk = getMainnetSdk(ethers.getDefaultProvider() as any);
console.log(`DAI supply is`, (await sdk.dai.totalSupply()).toString());
```

It works just fine but we need to disable typecheck here to make it happen, otherwise it complains that Provider != Signer.

Consider using `signerOrProvider: Signer | Provider` as an argument here similarly to how `typechain` handles this.

**Comment by Pzixel** [comment]
Duplicate of  #63

I can try  creating a PR if you're into merging it

**Comment by krzkaczor** [comment]
@Pzixel yes please consider creating a PR. I will close this one.
